export const books = [
    {
        name: "Design émotionnel",
        author: "Jeremy Keith",
        id: "9-782212-128611",
        language: "FR",
        format: "hardcover",
    },
    {
        name: "You're my favourite client",
        author: "Mike Monteiro",
        id: "9-781937-557140",
        language: "ENG",
        format: "hardcover",
    },
    {
        name: "Responsive Design : Patterns & Principles",
        author: "Ethan Marcotte",
        id: "9-781937-557331",
        language: "ENG",
        format: "hardcover",
    },
    {
        name: "Designer for touch",
        author: "Josh Clark",
        id: "9-781937-557287",
        language: "ENG",
        format: "hardcover",
    },
    {
        name: "La phase de recherche en web design",
        author: "Erika Hall",
        id: "9-782212-141467",
        language: "ENG",
        format: "hardcover",
    },
    {
        name: "Mobile first",
        author: "Luke Wroblewski",
        id: "9-782212-134063",
        language: "FR",
        format: "hardcover",
    },
    {
        name: "Métier Web Designer",
        author: "Mike Monteiro",
        id: "9-782212-135275",
        language: "FR",
        format: "hardcover",
    },
    {
        name: "Responsible Responsive Design",
        author: "Scott Jehl",
        id: "9-781937-557164",
        language: "ENG",
        format: "hardcover",
    },
    {
        name: "Going responsive",
        author: "Karen McGrane",
        id: "9-781937-557300",
        language: "ENG",
        format: "hardcover",
    },
    {
        name: "On web typography",
        author: "Jason Santa Maria",
        id: "9-781937-557065",
        language: "ENG",
        format: "hardcover",
    },
];
