export const books = [
    {
        id: 0,
        title: "Design émotionnel",
        author: "Aaron Walter",
        ISBN: "9-782212-128611",
        language: "FR",
        hardcover: true,
        ebook: false,
        URL: "https://images-na.ssl-images-amazon.com/images/I/61wMJ4uS4QL.jpg",
        available: true,
    },
    {
        id: 1,
        title: "You're my favourite client",
        author: "Mike Monteiro",
        ISBN: "9-781937-557140",
        language: "ENG",
        hardcover: true,
        ebook: false,
        URL:
            "https://cdn.shopify.com/s/files/1/0051/7692/products/ABA-cover-12_160x@3x.png?v=1463456298",
        available: true,
    },
    {
        id: 2,
        title: "Responsive Design : Patterns & Principles",
        author: "Ethan Marcotte",
        ISBN: "9-781937-557331",
        language: "ENG",
        hardcover: true,
        ebook: false,
        URL:
            "https://i.pinimg.com/736x/3b/01/d4/3b01d44fcc14949370db3079c843f51f.jpg",
        available: true,
    },
    {
        id: 3,
        title: "Designer for touch",
        author: "Josh Clark",
        ISBN: "9-781937-557287",
        language: "ENG",
        hardcover: true,
        ebook: false,
        URL:
            "https://cdn.shopify.com/s/files/1/0051/7692/products/ABA-cover-14_100x@3x.png?v=1463456340",
        available: true,
    },
    {
        id: 4,
        title: "La phase de recherche en web design",
        author: "Erika Hall",
        ISBN: "9-782212-141467",
        language: "ENG",
        hardcover: true,
        ebook: false,
        URL:
            "https://images-na.ssl-images-amazon.com/images/I/41pP1DMdMCL._SX319_BO1,204,203,200_.jpg",
        available: false,
    },
    {
        id: 5,
        title: "Mobile first",
        author: "Luke Wroblewski",
        ISBN: "9-782212-134063",
        language: "FR",
        hardcover: false,
        ebook: true,
        URL: "https://static.lukew.com/gfx-mobilefirst2_2x.png",
        available: false,
    },
    {
        id: 6,
        title: "Métier Web Designer",
        author: "Mike Monteiro",
        ISBN: "9-782212-135275",
        language: "FR",
        hardcover: false,
        ebook: true,
        URL: "https://images-na.ssl-images-amazon.com/images/I/814eWZI9wKL.jpg",
        available: false,
    },
    {
        id: 7,
        title: "Responsible Responsive Design",
        author: "Scott Jehl",
        ISBN: "9-781937-557164",
        language: "ENG",
        hardcover: false,
        ebook: true,
        URL:
            "https://cdn.shopify.com/s/files/1/0051/7692/products/ABA-cover-13_100x@3x.png?v=1463456319",
        available: false,
    },
    {
        id: 8,
        title: "Going responsive",
        author: "Karen McGrane",
        ISBN: "9-781937-557300",
        language: "ENG",
        hardcover: false,
        ebook: true,
        URL:
            "https://cdn.shopify.com/s/files/1/0051/7692/products/ABA-cover-16_d5151198-b8b7-4a41-8b46-3c3859540518_100x@3x.png?v=1463456383",
        available: true,
    },
    {
        id: 9,
        title: "On web typography",
        author: "Jason Santa Maria",
        ISBN: "9-781937-557065",
        language: "ENG",
        hardcover: false,
        ebook: true,
        URL: "https://covers.oreillystatic.com/images/9781937557065/lrg.jpg",
        available: false,
    },
];
